#ifndef EXT_INT_CFG_H_
#define EXT_INT_CFG_H_


#define    GLOBAL_INTERRUPT            GLOBAL_INTERRUPT_ENABLE   
 
#define    EXTERNAL_INT0_TRIGGER       INT0_TRIGGER_RISING_EDGE

#define    EXTERNAL_INT1_TRIGGER       INT0_TRIGGER_RISING_EDGE

#define    EXTERNAL_INT2_TRIGGER       INT0_TRIGGER_RISING_EDGE



#endif